logging:
  level:
    org.springframework: ERROR

cli:
  cliConfiguration:
    templatesFolder: null
    saveFormat: NORMALIZED
    interactive: true
  systems:
    - name: testDb
      endpoint: "jdbc:mysql://localhost:3306/"
      user: "root"
      password: "root"
    - name: anotherDb
      endpoint: "jdbc:mysql://localhost:3306/"
      user: "root"
      password: "root"
  platform:
    services:
      registry:
        url: http://localhost:8001
  template:
    owner:
      id: "testId"
      name: "456123"
  env:
    custom: customVariable
