logging:
  level:
    root: ERROR
    org.springframework: ERROR

cli:
  config:
    pluginFolder: ""
    templateFolder: ""
  systems:
    - testdb:
        url: "jdbc:mysql://localhost:3306/"
        user: "root"
        password: "root"

odm:
  user:
    name: "Andrea Gioa"
    email: "andrea.gioia@quantyca.it"
    namespace: "org.odm"