logging:
  level:
    org.springframework: ERROR

cli:
  cliConfiguration:
    templatesFolder: null
    saveFormat: NORMALIZED
  systems:
    - name: testDb
      endpoint: "jdbc:mysql://localhost:3306/"
      user: "root"
      password: "root"
    - name: anotherDb
      endpoint: "jdbc:mysql://localhost:3306/"
      user: "root"
      password: "root"
  env:
    custom: customVariable
